---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(ggdendro)
library(cluster)
library(factoextra)
```

```{r}
df <- iris
```

```{r}
head(df)
```

```{r}
colnames(df)
```


```{r}
ggplot(df, aes(Petal.Length, Petal.Width)) + geom_point(aes(col=Species), size=2) + ggtitle("IRIS DATASET")
```

```{r}
set.seed(101)
irisCluster <- kmeans(df[,1:4], center=3, nstart=20)
irisCluster
```


```{r}
table(irisCluster$cluster, df$Species)
```

```{r}
clusplot(iris, irisCluster$cluster, color=T, shade=T, labels=0, lines=0, main="CLUSTERING PLOT")
```

```{r}
tot.withinss <- vector(mode="character", length=10)
for (i in 1:10){
  irisCluster <- kmeans(df[,1:4], center=i, nstart=20)
  tot.withinss[i] <- irisCluster$tot.withinss
}
plot(1:10, tot.withinss, type="b", pch=19, main="ELBOW GRAPH")
```

```{r}
irisCluster <- kmeans(df[,1:4], center=3, nstart=20)
fviz_silhouette(silhouette(irisCluster$cluster, dist(df[,1:4])), main="SILHOUETTE")
```

```{r}
#dist method: {euclidean, maximum, manhattan, canberra, binary, minkowski}
#hclust method: {single, complete, average}

hiris <- hclust(dist(df[,1:4], method="minkowski"),
                method="complete")
plot(hiris, hang = -1, cex = 0.6, main ="DENDOGRAM")
```
```{r}
library(factoextra)
data("multishapes")
dbs <- multishapes[, 1:2]
plot(dbs, main = "DENSITY POINTS")
```

```{r}
set.seed(123)
km.res <- kmeans(dbs, 5, nstart = 25)
fviz_cluster(km.res, dbs, ellipse = TRUE, geom = "point", main="KMEANS ON DENSITY POINTS")
```

```{r}
library(fpc)
plot(
  fpc::dbscan(dbs, eps=0.15, MinPts = 5),
  dbs, 
  main = "DBSCAN", 
  frame = FALSE
)
```


