---
title: "A first look at a neural network"
output: 
  html_notebook: 
    theme: cerulean
    highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(keras)
model <- keras_model_sequential() %>%

  layer_conv_2d(filters = 32, kernel_size = c(3, 3), activation = "relu",
                input_shape = c(28, 28, 1)) %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  layer_conv_2d(filters = 64, kernel_size = c(3, 3), activation = "relu") %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  layer_conv_2d(filters = 64, kernel_size = c(3, 3), activation = "relu")
```


```{r}
model
```

```{r}
model <- model %>%
layer_flatten() %>%
layer_dense(units = 64, activation = "relu") %>% layer_dense(units = 10, activation = "softmax")
```

```{r}
model
```

```{r}
mnist <- dataset_mnist()
c(c(train_images, train_labels), c(test_images, test_labels)) %<-% mnist

```

```{r}

train_images <- array_reshape(train_images, c(60000, 28, 28, 1))
train_images <- train_images / 255

test_images <- array_reshape(test_images, c(10000, 28, 28, 1)) 
test_images <- test_images / 255

train_labels <- to_categorical(train_labels) 
test_labels <- to_categorical(test_labels)

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

```


```{r}
model %>% fit(
  train_images, train_labels,
  epochs = 5, batch_size=64
)
```


```{r}
results <- model %>% evaluate(test_images, test_labels)
results
```




